### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by nathanredblur** [Kwintenvdb/homebridge-divoom#10]
**Describe The Bug:**

it's not possible to install this plugin

**To Reproduce:**

`npm i -g homebridge-divoom`
I also try installing mocha globally
`npm i -g chai mocha ts-node @types/chai @types/mocha`

**Expected behavior:**
success

**Logs:**
```
npm install -g homebridge-divoom
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/juanito-alimaña/.nvm/versions/node/v16.15.0/bin/node /Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/juanito-alimaña/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! npm WARN cleanup Failed to remove some directories [
npm ERR! npm WARN cleanup   [
npm ERR! npm WARN cleanup     '/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/node-divoom-timebox-evo',
npm ERR! npm WARN cleanup     [Error: EINVAL: invalid argument, rmdir '/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/node-divoom-timebox-evo/node_modules/image-q/dist/types/src/palette'] {
npm ERR! npm WARN cleanup       errno: -22,
npm ERR! npm WARN cleanup       code: 'EINVAL',
npm ERR! npm WARN cleanup       syscall: 'rmdir',
npm ERR! npm WARN cleanup       path: '/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/node-divoom-timebox-evo/node_modules/image-q/dist/types/src/palette'
npm ERR! npm WARN cleanup     }
npm ERR! npm WARN cleanup   ]
npm ERR! npm WARN cleanup ]
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/juanito-alimaña/.npm/_cacache/tmp/git-cloneI4Lm3c
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run test && npm run build
npm ERR! npm ERR! > node-divoom-timebox-evo@0.3.0 test
npm ERR! npm ERR! > TS_NODE_COMPILER_OPTIONS='{"module":"commonjs"}' mocha --require ts-node/register test/*.spec.ts test/**/*.spec.ts
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR!
npm ERR! npm ERR! TSError: ⨯ Unable to compile TypeScript:
npm ERR! npm ERR! test/index.spec.ts(1,24): error TS2307: Cannot find module 'chai' or its corresponding type declarations.
npm ERR! npm ERR! test/index.spec.ts(20,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(21,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(25,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(29,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(33,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(37,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(41,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(45,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(49,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(53,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(57,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(61,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR! test/index.spec.ts(65,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! npm ERR!
npm ERR! npm ERR!     at createTSError (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/ts-node/src/index.ts:859:12)
npm ERR! npm ERR!     at reportTSError (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/ts-node/src/index.ts:863:19)
npm ERR! npm ERR!     at getOutput (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/ts-node/src/index.ts:1077:36)
npm ERR! npm ERR!     at Object.compile (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/ts-node/src/index.ts:1433:41)
npm ERR! npm ERR!     at Module.m._compile (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/ts-node/src/index.ts:1617:30)
npm ERR! npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR! npm ERR!     at Object.require.extensions.<computed> [as .ts] (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/ts-node/src/index.ts:1621:12)
npm ERR! npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR! npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR! npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR! npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR! npm ERR!     at Object.exports.requireOrImport (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
npm ERR! npm ERR!     at async Object.exports.loadFilesAsync (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
npm ERR! npm ERR!     at async singleRun (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
npm ERR! npm ERR!     at async Object.exports.handler (/Users/juanito-alimaña/.nvm/versions/node/v16.15.0/lib/node_modules/mocha/lib/cli/run.js:370:5)
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/juanito-alimaña/.npm/_logs/2022-11-11T17_47_56_604Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanito-alimaña/.npm/_logs/2022-11-11T17_47_51_245Z-debug-0.log
```

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v1.5.1
* **Node.js Version**: 16.15.0
* **NPM Version**: 9.1.1
* **Operating System**: macOS

**Comment by Kwintenvdb** [comment]
This plugin only works with Node.js v12.x right now unfortunately. Feel free to fork and create a PR if you'd like to add support for later versions of Node.js.
